openapi: 3.0.3
info:
  title: Video to Workinstructions API
  description: API for converting videos to workinstructions
  version: 1.0.0-RC2
paths:
  /v1/video/videoAnalysis:
    post:
      tags:
        - videoAnalysis
      summary: Start Video Analysis
      description: >-
        Starts the video to workinstruction conversion and returns an ID and a
        Halerium Path URL at which the product definition can be found and
        edited.
      operationId: startVideoAnalysis
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_startVideoAnalysis'
      responses:
        '201':
          description: >-
            Product Definition Name, Run ID, and Halerium Path URL at which the
            product definition can be found and edited upon pipeline completion.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoAnalysisInformation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - videoAnalysis
      summary: Get all exisiting Video Analyses or for a specific tag.
      description: >-
        Returns a list of all video analyses or for a specific tag. If tag is
        not set, returns all video analyses.
      operationId: getVideoAnalyses
      parameters:
        - name: tag
          in: query
          required: false
          schema:
            type: string
            nullable: true
          description: The tag to filter video analyses by
      responses:
        '200':
          description: >-
            Product Definition Name, Run ID, and Halerium Path URL of all active
            Runs for a specific tag. If tag is not set, returns all active runs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoAnalysisInformation'
                title: Response Getvideoanalyses
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/video/videoAnalysis/{id}:
    get:
      tags:
        - videoAnalysis
      summary: Get the current Video Analysis result.
      description: Returns the current result of the video analysis with the given ID.
      operationId: getVideoAnalysis
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: The product definition model of the video analysis.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoAnalysisResult'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - videoAnalysis
      summary: Delete the Video Analysis.
      description: >-
        Deletes the video analysis run with the given ID. Also cancels the run
        if it is still running.
      operationId: deleteVideoAnalysis
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: Message indicating when the run was deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoAnalysisDeleted'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/video/docx/{id}:
    get:
      tags:
        - videoAnalysis
      summary: Get the product definition in docx format
      description: >-
        Returns the product definition in docx format. DOCX generation first has
        to be triggered in the user review board!
      operationId: getDocx
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: The product definition in docx format.
          content:
            application/json:
              schema: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Activity:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        activityType:
          $ref: '#/components/schemas/StepTypeActivityTypeEnum'
        steps:
          items:
            $ref: '#/components/schemas/Step'
          type: array
          title: Steps
      type: object
      required:
        - name
        - description
        - activityType
        - steps
      title: Activity
    Body_startVideoAnalysis:
      properties:
        video:
          type: string
          format: binary
          title: Video
          description: Video file to be analyzed
        productDefinitionName:
          type: string
          title: Productdefinitionname
          description: Name of the product definition
        videoPath:
          type: string
          title: Videopath
          description: Path to the video file on client's system
        tag:
          type: string
          nullable: true
      type: object
      required:
        - video
        - productDefinitionName
        - videoPath
      title: Body_startVideoAnalysis
    Equipment:
      properties:
        name:
          type: string
          title: Name
        position:
          type: integer
          title: Position
        inventoryNumber:
          type: string
          title: Inventorynumber
        quantity:
          $ref: '#/components/schemas/Quantity'
      type: object
      required:
        - name
        - position
        - inventoryNumber
        - quantity
      title: Equipment
    ErrorResponse:
      properties:
        detail:
          type: string
          title: Detail
          default: ''
        code:
          type: integer
          title: Code
          default: 0
        message:
          type: string
          title: Message
          default: ''
      type: object
      title: ErrorResponse
    Message:
      properties:
        currentStep:
          type: string
          nullable: true
        currentStatus:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
      type: object
      title: Message
    ProductDefinition:
      properties:
        activities:
          items:
            $ref: '#/components/schemas/Activity'
          type: array
          title: Activities
      type: object
      required:
        - activities
      title: ProductDefinition
    Quantity:
      properties:
        value:
          type: integer
          title: Value
        unit:
          $ref: '#/components/schemas/Unit'
      type: object
      required:
        - value
        - unit
      title: Quantity
    SourceEnum:
      type: string
      enum:
        - URL
        - PATH
      title: SourceEnum
    StatusEnum:
      type: string
      enum:
        - started
        - running
        - finished
        - pending
        - failed
        - cancelled
        - success
      title: StatusEnum
      x-enum-varnames:
        - started
        - running
        - finished
        - pending
        - failed
        - cancelled
        - success
    Step:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        stepInformation:
          type: string
          title: Stepinformation
        stepImage:
          $ref: '#/components/schemas/StepImage'
        stepVideo:
          $ref: '#/components/schemas/StepVideo'
        stepType:
          $ref: '#/components/schemas/StepTypeActivityTypeEnum'
        equipment:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
          title: Equipment
      type: object
      required:
        - name
        - description
        - stepInformation
        - stepImage
        - stepVideo
        - stepType
        - equipment
      title: Step
    StepImage:
      properties:
        imageString:
          type: string
          title: Imagestring
        source:
          $ref: '#/components/schemas/SourceEnum'
      type: object
      required:
        - imageString
        - source
      title: StepImage
    StepTypeActivityTypeEnum:
      type: string
      enum:
        - SETUP
        - PRODUCTION
        - TEAR DOWN
        - REWORK
        - QUALITY CHECK
      title: StepTypeActivityTypeEnum
    StepVideo:
      properties:
        videoString:
          type: string
          title: Videostring
        source:
          $ref: '#/components/schemas/SourceEnum'
        start:
          type: string
          title: Start
        end:
          type: string
          title: End
      type: object
      required:
        - videoString
        - source
        - start
        - end
      title: StepVideo
    Unit:
      properties:
        name:
          type: string
          title: Name
      type: object
      required:
        - name
      title: Unit
    VideoAnalysisDeleted:
      properties:
        videoAnalysisId:
          type: string
          title: Videoanalysisid
        prodDefName:
          type: string
          title: Proddefname
        message:
          $ref: '#/components/schemas/Message'
          nullable: true
      type: object
      required:
        - videoAnalysisId
        - prodDefName
      title: VideoAnalysisDeleted
    VideoAnalysisInformation:
      properties:
        videoAnalysisId:
          type: string
          title: Videoanalysisid
        prodDefName:
          type: string
          title: Proddefname
        createdAt:
          type: string
          format: date-time
          title: Createdat
          description: ISO8601 compliant datetime string
        tag:
          type: string
          nullable: true
        haleriumPathUrl:
          type: string
          title: Haleriumpathurl
        status:
          $ref: '#/components/schemas/StatusEnum'
      type: object
      required:
        - videoAnalysisId
        - prodDefName
        - createdAt
        - haleriumPathUrl
        - status
      title: VideoAnalysisInformation
    VideoAnalysisResult:
      properties:
        videoAnalysisId:
          type: string
          title: Videoanalysisid
        prodDefName:
          type: string
          title: Proddefname
        status:
          $ref: '#/components/schemas/StatusEnum'
        message:
          $ref: '#/components/schemas/Message'
          nullable: true
        productDefinition:
          $ref: '#/components/schemas/ProductDefinition'
          nullable: true
      type: object
      required:
        - videoAnalysisId
        - prodDefName
        - status
      title: VideoAnalysisResult
